insert into questions(question_title) values ('start'),('name'),('gender'),('contact')
insert into questions(question_title) values ('birth')
insert into questions(question_title) values ('taklif')
insert into questions(question_title) values ('up_us_name')
insert into questions(question_title) values ('up_gen_name')